config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'pages#home'
  get 'tweets', to: 'pages#tweets'

  namespace :api do
    namespace :v1 do
      resources :tweets, only: %i[index show create destroy]
      resources :taggings, only: %i[index create destroy]
      get 'tag_counts', to: 'taggings#tag_counts'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/liked_tweet.rb
class LikedTweet < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  scope :ordered, -> { order(tweet_id: :desc) }
  scope :deleted, -> (bool) { bool ? where.not(deleted_at: nil) : where(deleted_at: nil) }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :liked_tweets, through: :taggings

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :liked_tweet

  validates :tag, presence: true
  validates :liked_tweet, presence: true
  validates :tag, uniqueness: { scope: :liked_tweet }
end

app/models/twitter_object.rb
class TwitterObject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[twitter]

  has_many :liked_tweets
  has_many :tags, through: :liked_tweets

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user| # TODO check what provider returns
      user.email = auth.info.email || '' # to bypass not null constraint on the db
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.nickname

      # image, etc.

      # user.skip_confirmation! # if using confirmable
    end
  end

  def email_required?
    false # some twitter users won't have an email. should probably distinguish twitter auth users. TODO
  end

  def most_recently_liked_tweet_id
    liked_tweets.ordered.first&.tweet_id
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/api/v1/taggings_controller.rb
class Api::V1::TaggingsController < Api::V1::BaseController
  def index
    liked_tweet = LikedTweet.find_by!(tweet_id: params[:tweet_id])
    taggings = liked_tweet.taggings
    render json: TaggingSerializer.new(taggings)
  end

  def create
    taggings = CreateTaggingsOrchestratorService.call!(
      tag_names: tagging_params[:tag_names],
      liked_tweet_id: tagging_params[:liked_tweet_id]
    )
    render json: TaggingSerializer.new(taggings)
    # handle error
  end

  def destroy
    tagging = Tagging.find_by(id: params[:id])
    if tagging.liked_tweet.user == current_user && tagging.destroy!
      render body: nil, status: :no_content # https://stackoverflow.com/a/33805840
    else
      render json: {error: 'Could not destroy'}
    end
  end

  def tag_counts
    tag_names = current_user.tags.group(:name).order(count_all: :desc).count.keys
    render json: {data: tag_names}
  end

  private
  # build this out more
  def tagging_params
    params.require(:tagging).permit(:tag_names, :liked_tweet_id)
  end
end

app/controllers/api/v1/tweets_controller.rb
class Api::V1::TweetsController < Api::V1::BaseController
  DEFAULT_LIMIT = 10

  def index
    tweets = if params[:tag].present?
      tag = Tag.find_by(name: params[:tag])
      tag.liked_tweets.where(user: current_user).includes(:tags).deleted(false).ordered
    else
      current_user.liked_tweets.includes(:tags).deleted(false).ordered
    end

    total_count = tweets.size
    page = params[:page].present? ? params[:page].to_i : 1
    total_pages = (total_count/DEFAULT_LIMIT) + 1
    offset = (page * DEFAULT_LIMIT) - DEFAULT_LIMIT
    has_more = page < total_pages
    limited_tweets = tweets.limit(DEFAULT_LIMIT).offset(offset)

    count = limited_tweets.size
    count_data = {limit: DEFAULT_LIMIT, count: count, page: page, total_pages: total_pages, has_more: has_more}


    render json: count_data.merge(LikedTweetSerializer.new(limited_tweets))
  end

  def show
    tweet = current_user.liked_tweets.find_by(id: params[:id])
    render json: LikedTweetSerializer.new(tweet)
  end

  def create
    LikedTweetPopulator.new(user: current_user).fetch_recently_liked_tweets
  end

  def destroy
    liked_tweet = LikedTweet.find_by(id: params[:id])
    if liked_tweet.user == current_user && liked_tweet.update!(deleted_at: Time.current)
      render body: nil, status: :no_content # https://stackoverflow.com/a/33805840
    else
      render json: {error: 'Could not destroy'}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def tweets
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect(@user, event: :authentication)
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra') # extra provides additional info in the response
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApiGetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='container'>
      <% if notice %>
        <div class="notice alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <!-- <script sync src="https://platform.twitter.com/widgets.js"></script> script to use twttr.widgets-->
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <%= javascript_pack_tag 'hello_react' %>
<% end %>

<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<div id="twits"></div>

<!-- <blockquote class="twitter-tweet"><p lang="en" dir="ltr">In elementary cat geometry, the property of being purrpendicular is the relationship between two fe-lines which meet at a right angle (90 degrees).<a href="https://twitter.com/hashtag/WednesdayWisdom?src=hash&amp;ref_src=twsrc%5Etfw">#WednesdayWisdom</a> <a href="https://t.co/nxl22iYyEE">pic.twitter.com/nxl22iYyEE</a></p>&mdash; Dick King-Smith HQ (@DickKingSmith) <a href="https://twitter.com/DickKingSmith/status/1232613076630953984?ref_src=twsrc%5Etfw">February 26, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">this dog doesn&#39;t need a sled, he is one<br>(Naturhotel Forsthofgut FB) <a href="https://t.co/Osq7qlHFF0">pic.twitter.com/Osq7qlHFF0</a></p>&mdash; Humor And Animals (@humorandanimals) <a href="https://twitter.com/humorandanimals/status/1231208173597548546?ref_src=twsrc%5Etfw">February 22, 2020</a></blockquote> -->

<!-- <a class="twitter-timeline" href="https://twitter.com/mikevallano/likes?ref_src=twsrc%5Etfw">Mah liked tweets</a> -->

app/views/pages/tweets.html.erb
<%= javascript_pack_tag 'tweets' %>
<%#= stylesheet_pack_tag 'pages' %>
<div id="tweets"></div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler"
          type="button" data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <% if current_user %>
        <%= link_to current_user.username, edit_user_registration_path, class: 'nav-item nav-link' %>
        <%= link_to 'show mah tweets', tweets_path, class: 'nav-item nav-link' %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: 'nav-item nav-link' %>
      <% end %>
    </div>
  </div>
</nav>